---
logging:
  level: DEBUG
  loggers:
    com.programmervsworld: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

database:
  driverClass: "org.h2.Driver"
  url: "jdbc:h2:file:~/alarmsdb"
  user: sa
  password: ""
  
  properties:
    charSet: UTF-8
    hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.hbm2ddl.auto: "update"
    hibernate.dialect: org.hibernate.dialect.H2Dialect