---
logging:
  level: INFO
  loggers:
    com.programmervsworld: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

database:
  driverClass: "org.mariadb.jdbc.Driver"
  user: "shedlab"
  password: "fairlane"
  url: "jdbc:mariadb://raspberrypi:3306/spindle"
  properties:
    charSet: UTF-8