---
logging:
  level: INFO
  loggers:
    com.programmervsworld: DEBUG

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

database:
  driverClass: "org.apache.derby.jdbc.EmbeddedDriver"
  url: " jdbc:derby:alarmsdb;create=true"
  user: "root"
  password: "root"
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: "create-drop"